
'use client';
import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { 
  BookOpenText, 
  Gavel, 
  Scale, 
  FileText, 
  Mountain, 
  Send, 
  Mic, 
  Paperclip, 
  Sparkles,
  ChevronDown,
  History,
  Plus
} from 'lucide-react';

export default function LegalAdvisor() {
  const [messages, setMessages] = useState([
    {
      id: '1',
      content: 'Summarize the key provisions of the Nepal Labor Act, 2074 regarding employee rights.',
      sender: 'user',
      timestamp: new Date(2025, 6, 20, 10, 30),
    },
    {
      id: '2',
      content: 'The Nepal Labor Act, 2074 contains several key provisions protecting employee rights:\n\n1. **Working Hours** - Maximum 8 hours/day or 48 hours/week\n2. **Minimum Wage** - As prescribed by government authorities\n3. **Leave Entitlement** - Annual, sick, and maternity leave provisions\n4. **Safety Measures** - Employer must provide safe working conditions\n5. **Termination** - Specific procedures and compensation requirements\n6. **Discrimination** - Prohibition against gender-based pay disparity',
      sender: 'ai',
      timestamp: new Date(2025, 6, 20, 10, 32),
      citations: [
        { reference: 'Labor Act, 2074 § 24', excerpt: 'Maximum working hours shall not exceed eight hours a day or forty-eight hours a week.' },
        { reference: 'Labor Act, 2074 § 52', excerpt: 'Every worker shall be entitled to annual leave with pay at the rate of one day for every twenty days of work performed.' },
        { reference: 'Labor Act, 2074 § 45', excerpt: 'No discrimination shall be made between male and female workers in respect of remuneration for the same work or work of similar nature.' }
      ]
    }
  ]);
  
  const [inputValue, setInputValue] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [activeCitation, setActiveCitation] = useState<number | null>(null);
  const [isHistoryOpen, setIsHistoryOpen] = useState(true);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  
  const chatHistory = [
    { id: '1', title: 'Summarize the key provisions...', date: 'Today' },
    { id: '2', title: 'Draft a rental agreement for...', date: 'Yesterday' },
    { id: '3', title: 'Explain Article 16 of the...', date: 'Jul 18' },
    { id: '4', title: 'Requirements for business...', date: 'Jul 15' },
    { id: '5', title: 'How to file a property...', date: 'Jul 12' },
  ];

  const handleSendMessage = () => {
    if (!inputValue.trim()) return;
    
    const userMessage = {
      id: Date.now().toString(),
      content: inputValue,
      sender: 'user',
      timestamp: new Date(),
    };
    
    setMessages(prev => [...prev, userMessage]);
    setInputValue('');
    setIsLoading(true);
    
    // Simulate AI response
    setTimeout(() => {
      const aiMessage = {
        id: Date.now().toString(),
        content: 'This is a sample response from the legal AI advisor. In a real application, this would be generated by your Genkit backend with accurate legal information.',
        sender: 'ai',
        timestamp: new Date(),
        citations: [
          { reference: 'Constitution of Nepal, Article 18', excerpt: 'Sample excerpt text from a legal document would appear here...' },
          { reference: 'Civil Code, 2074 § 45', excerpt: 'Another relevant legal citation would be displayed in this section...' }
        ]
      };
      
      setMessages(prev => [...prev, aiMessage]);
      setIsLoading(false);
    }, 1500);
  };

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  return (
    <div className="flex h-[calc(100vh-64px)] bg-gradient-to-br from-gray-50 to-legal-primary/5 dark:from-legal-dark dark:to-gray-900">
      {/* Sidebar */}
      <div className={`w-72 bg-white dark:bg-gray-900 border-r border-gray-200 dark:border-gray-800 flex flex-col transition-all duration-300 ${isHistoryOpen ? 'translate-x-0' : '-translate-x-full absolute'}`}>
        <div className="p-4 border-b border-gray-200 dark:border-gray-800">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-xl font-bold flex items-center gap-2">
              <History className="h-5 w-5" />
              Chat History
            </h2>
            <Button 
              variant="outline" 
              size="icon" 
              className="h-8 w-8"
              onClick={() => setIsHistoryOpen(false)}
            >
              <ChevronDown className="h-4 w-4 rotate-90" />
            </Button>
          </div>
          
          <Button className="w-full bg-legal-primary hover:bg-legal-primary/90 mb-4">
            <Plus className="h-4 w-4 mr-2" />
            New Chat
          </Button>
          
          <div className="relative">
            <Input 
              placeholder="Search chats..." 
              className="pl-8"
            />
            <svg
              className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-400"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
            >
              <circle cx="11" cy="11" r="8" />
              <path d="m21 21-4.3-4.3" />
            </svg>
          </div>
        </div>
        
        <div className="flex-1 overflow-y-auto p-2">
          {chatHistory.map((chat) => (
            <div 
              key={chat.id}
              className="p-3 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 cursor-pointer transition-colors mb-1"
            >
              <div className="font-medium truncate">{chat.title}</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">{chat.date}</div>
            </div>
          ))}
        </div>
        
        <div className="p-4 border-t border-gray-200 dark:border-gray-800 text-center text-xs text-gray-500 dark:text-gray-400">
          <p>© 2025 SMS Neotech</p>
          <p className="mt-1">Disclaimer: Responses may be inaccurate. Verify with official legal sources.</p>
        </div>
      </div>
      
      {/* Main Content */}
      <div className="flex-1 flex flex-col">
        {/* Header */}
        <header className="bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-800 p-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Button 
              variant="outline" 
              size="icon" 
              className="h-8 w-8 md:hidden"
              onClick={() => setIsHistoryOpen(true)}
            >
              <History className="h-4 w-4" />
            </Button>
            <div className="flex items-center gap-2">
              <div className="bg-gradient-to-r from-legal-primary to-legal-secondary p-2 rounded-lg">
                <Gavel className="h-6 w-6 text-white" />
              </div>
              <h1 className="text-xl font-bold">Legal Advisor</h1>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            <div className="hidden md:flex items-center gap-1 text-sm bg-gray-100 dark:bg-gray-800 px-3 py-1 rounded-full">
              <div className="h-2 w-2 rounded-full bg-green-500"></div>
              <span>Gemini Flash</span>
            </div>
            <Button variant="outline" className="hidden md:flex">
              <Sparkles className="h-4 w-4 mr-2" />
              AI Model
            </Button>
          </div>
        </header>
        
        {/* Chat Area */}
        <div className="flex-1 overflow-y-auto p-4 md:p-6">
          <div className="max-w-3xl mx-auto">
            <div className="flex justify-center mb-8">
              <div className="text-center">
                <div className="bg-gradient-to-r from-legal-primary to-legal-secondary p-3 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
                  <Mountain className="h-8 w-8 text-white" />
                </div>
                <h2 className="text-2xl font-bold">Nepali Legal Advisor</h2>
                <p className="text-gray-500 dark:text-gray-400 mt-2">
                  Ask questions about Nepalese law, constitution, or legal procedures
                </p>
              </div>
            </div>
            
            <div className="space-y-6">
              {messages.map((message) => (
                <motion.div
                  key={message.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className={`flex ${message.sender === 'user' ? 'justify-end' : 'justify-start'}`}
                >
                  <div className={`max-w-[85%] ${message.sender === 'user' ? 'ml-auto' : ''}`}>
                    {message.sender === 'ai' && (
                      <div className="flex items-center gap-2 mb-2 text-sm text-gray-500 dark:text-gray-400">
                        <div className="bg-gradient-to-r from-legal-primary to-legal-secondary p-1 rounded-full">
                          <Sparkles className="h-3 w-3 text-white" />
                        </div>
                        <span>Gemini Flash • Today</span>
                      </div>
                    )}
                    
                    <Card 
                      className={
                        message.sender === 'user' 
                          ? 'bg-gray-50 dark:bg-gray-800 border-gray-200 dark:border-gray-700' 
                          : 'bg-gradient-to-br from-white to-legal-primary/10 dark:from-gray-900 dark:to-legal-primary/20 border-legal-primary/20'
                      }
                    >
                      <CardContent className="p-4">
                        <div className={`${message.sender === 'ai' ? 'space-y-4' : ''}`}>
                          {message.content.split('\n').map((line, i) => (
                            <p key={i} className="mb-2 last:mb-0">{line}</p>
                          ))}
                          
                          {message.citations && message.sender === 'ai' && (
                            <div className="mt-4">
                              <div className="flex items-center gap-2 text-sm font-medium mb-2">
                                <BookOpenText className="h-4 w-4 text-legal-primary" />
                                Legal References
                              </div>
                              
                              <div className="space-y-3">
                                {message.citations.map((citation, idx) => (
                                  <Card 
                                    key={idx} 
                                    className={`bg-white dark:bg-gray-800 border-legal-primary/20 cursor-pointer transition-all hover:border-legal-primary ${activeCitation === idx ? 'border-legal-primary' : ''}`}
                                    onClick={() => setActiveCitation(activeCitation === idx ? null : idx)}
                                  >
                                    <CardContent className="p-3">
                                      <div className="font-medium flex items-center justify-between">
                                        <span>{citation.reference}</span>
                                        <ChevronDown className={`h-4 w-4 transition-transform ${activeCitation === idx ? 'rotate-180' : ''}`} />
                                      </div>
                                      
                                      <AnimatePresence>
                                        {activeCitation === idx && (
                                          <motion.div
                                            initial={{ height: 0, opacity: 0 }}
                                            animate={{ height: 'auto', opacity: 1 }}
                                            exit={{ height: 0, opacity: 0 }}
                                            className="overflow-hidden"
                                          >
                                            <div className="mt-2 pt-2 border-t border-gray-200 dark:border-gray-700">
                                              <p className="text-sm">{citation.excerpt}</p>
                                              <Button variant="link" className="text-legal-primary p-0 h-auto mt-2">
                                                View Full Document
                                              </Button>
                                            </div>
                                          </motion.div>
                                        )}
                                      </AnimatePresence>
                                    </CardContent>
                                  </Card>
                                ))}
                              </div>
                            </div>
                          )}
                        </div>
                      </CardContent>
                    </Card>
                    
                    {message.sender === 'user' && (
                      <div className="text-xs text-gray-500 dark:text-gray-400 mt-1 text-right">
                        {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </div>
                    )}
                  </div>
                </motion.div>
              ))}
              
              {isLoading && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="flex justify-start"
                >
                  <Card className="bg-gradient-to-br from-white to-legal-primary/10 dark:from-gray-900 dark:to-legal-primary/20 border-legal-primary/20 max-w-[85%]">
                    <CardContent className="p-4">
                      <div className="flex items-center space-x-2">
                        <div className="w-2 h-2 rounded-full bg-legal-primary animate-pulse"></div>
                        <div className="w-2 h-2 rounded-full bg-legal-primary animate-pulse delay-75"></div>
                        <div className="w-2 h-2 rounded-full bg-legal-primary animate-pulse delay-150"></div>
                        <span className="ml-2">Researching legal provisions...</span>
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              )}
              
              <div ref={messagesEndRef} />
            </div>
          </div>
        </div>
        
        {/* Input Area */}
        <div className="border-t border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 p-4">
          <div className="max-w-3xl mx-auto">
            <div className="flex gap-2 mb-3">
              <Button variant="secondary" className="rounded-full">
                <FileText className="h-4 w-4 mr-2" /> Draft a legal document
              </Button>
              <Button variant="secondary" className="rounded-full">
                <Scale className="h-4 w-4 mr-2" /> Explain Article 16
              </Button>
              <Button variant="secondary" className="rounded-full">
                <BookOpenText className="h-4 w-4 mr-2" /> Labor Act summary
              </Button>
            </div>
            
            <div className="relative">
              <Input
                value={inputValue}
                onChange={(e) => setInputValue(e.target.value)}
                placeholder="Type your message here... (Enter to send, Alt+Enter for new line)"
                className="pl-12 pr-24 py-5 rounded-xl"
                onKeyDown={(e) => e.key === 'Enter' && !e.altKey && handleSendMessage()}
              />
              
              <div className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400">
                <Mountain className="h-5 w-5" />
              </div>
              
              <div className="absolute right-2 top-1/2 transform -translate-y-1/2 flex gap-2">
                <Button variant="ghost" size="icon" className="text-gray-500 hover:text-legal-primary">
                  <Mic className="h-5 w-5" />
                </Button>
                <Button variant="ghost" size="icon" className="text-gray-500 hover:text-legal-primary">
                  <Paperclip className="h-5 w-5" />
                </Button>
                <Button 
                  className="bg-legal-primary hover:bg-legal-primary/90"
                  onClick={handleSendMessage}
                >
                  <Send className="h-4 w-4 mr-2" />
                  Send
                </Button>
              </div>
            </div>
            
            <div className="text-center mt-3 text-xs text-gray-500 dark:text-gray-400">
              <p>© 2025 SMS Neotech • Disclaimer: Responses may be inaccurate. Verify with official legal sources.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

    